import { type FieldDef, FieldInput } from "@/lib/categories/field-def";
import {
  Certification,
  ClarityGrade,
  ClaspType,
  Color,
  ColorGrade,
  CutGrade,
  Department,
  Features,
  MainStoneCreation,
  MainStoneTreatment,
  Metal,
  MetalPurity,
  NecklaceType,
  Occasion,
  Stone,
  StoneColor,
  StoneShape,
  Theme,
  YesNo,
} from "@/lib/enums/product-aspects";

export const necklacesPendantsFields: FieldDef[] = [
  { aspect: "Brand", input: FieldInput.Text },
  {
    aspect: "Department",
    input: FieldInput.Enum,
    options: Object.values(Department),
  },
  {
    aspect: "Metal",
    input: FieldInput.Enum,
    options: Object.values(Metal),
    required: true,
  },
  {
    aspect: "Metal Purity",
    input: FieldInput.Enum,
    options: Object.values(MetalPurity),
  },
  {
    aspect: "Main Stone",
    input: FieldInput.Enum,
    options: Object.values(Stone),
    required: true,
  },
  {
    aspect: "Main Stone Creation",
    input: FieldInput.Enum,
    options: Object.values(MainStoneCreation),
  },
  {
    aspect: "Main Stone Treatment",
    input: FieldInput.Enum,
    options: Object.values(MainStoneTreatment),
  },
  {
    aspect: "Main Stone Color",
    input: FieldInput.Enum,
    options: Object.values(StoneColor),
  },
  {
    aspect: "Main Stone Shape",
    input: FieldInput.Enum,
    options: Object.values(StoneShape),
  },
  { aspect: "Total Carat Weight", input: FieldInput.Text },
  { aspect: "Number of Gemstones", input: FieldInput.Text },
  {
    aspect: "Cut Grade",
    input: FieldInput.Enum,
    options: Object.values(CutGrade),
  },
  {
    aspect: "Color Grade",
    input: FieldInput.Enum,
    options: Object.values(ColorGrade),
  },
  {
    aspect: "Clarity Grade",
    input: FieldInput.Enum,
    options: Object.values(ClarityGrade),
  },
  {
    aspect: "Secondary Stone",
    input: FieldInput.Enum,
    options: Object.values(Stone),
  },
  {
    aspect: "Certification",
    input: FieldInput.Enum,
    options: Object.values(Certification),
  },
  { aspect: "Certification Number", input: FieldInput.Text },
  { aspect: "Theme", input: FieldInput.Enum, options: Object.values(Theme) },
  {
    aspect: "Occasion",
    input: FieldInput.Enum,
    options: Object.values(Occasion),
  },
  { aspect: "Color", input: FieldInput.Enum, options: Object.values(Color) },
  {
    aspect: "Features",
    input: FieldInput.Enum,
    options: Object.values(Features),
  },
  { aspect: "Vintage", input: FieldInput.Enum, options: Object.values(YesNo) },
  {
    aspect: "Personalized",
    input: FieldInput.Enum,
    options: Object.values(YesNo),
  },
  { aspect: "Country/Region of Manufacture", input: FieldInput.Text },
  { aspect: "MPN", input: FieldInput.Text },
  { aspect: "UPC", input: FieldInput.Text },
  { aspect: "California Prop 65 Warning", input: FieldInput.Text },
  {
    aspect: "Necklace Type",
    input: FieldInput.Enum,
    options: Object.values(NecklaceType),
  },
  { aspect: "Pendant/Locket", input: FieldInput.Text },
  { aspect: "Chain Length", input: FieldInput.Text },
  { aspect: "Length", input: FieldInput.Text },
  {
    aspect: "Clasp Type",
    input: FieldInput.Enum,
    options: Object.values(ClaspType),
  },
];
